#! /usr/bin/env python
# -*- coding: utf-8 -*-
#
# Smappee Controller © Autolog 2018-2023
#

import logging

# ============================== Custom Imports ===============================
try:
    import indigo  # noqa
except ImportError:
    pass

number = -1

debug_show_constants = False
debug_use_labels = False

# def constant_id(constant_label) -> int:  # Auto increment constant id
def constant_id(constant_label):  # Auto increment constant id

    global number
    if debug_show_constants and number == -1:
        indigo.server.log("Zigbee2MQTT Bridge Plugin internal Constant Name mapping ...", level=logging.DEBUG)
    number += 1
    if debug_show_constants:
        indigo.server.log(f"{number}: {constant_label}", level=logging.DEBUG)
    if debug_use_labels:
        return constant_label
    else:
        return number

# plugin Constants


try:
    # noinspection PyUnresolvedReferences
    import indigo
except ImportError:
    pass

# noinspection Duplicates




# INITIALISE = constant_id("INITIALISE")


ACCESS_TOKEN = constant_id("ACCESS_TOKEN")
ACCUMULATED_ENERGY_TOTAL = constant_id("ACCUMULATED_ENERGY_TOTAL")
ACCUM_UNITS = constant_id("ACCUM_UNITS")
ACTUATOR_IDS = constant_id("ACTUATOR_IDS")
ADDRESS = constant_id("ADDRESS")
ALWAYS_ON = constant_id("ALWAYS_ON")
API_VERSION = constant_id("API_VERSION")
APPLIANCE_IDS = constant_id("APPLIANCE_IDS")
APP_NAME = constant_id("APP_NAME")
BATTERY_LEVEL_LAST_UPDATED = constant_id("BATTERY_LEVEL_LAST_UPDATED")
CLIENT_ID = constant_id("CLIENT_ID")
COMMAND_END_THREAD = constant_id("COMMAND_END_THREAD")
COMMAND_GET_CONSUMPTION = constant_id("COMMAND_GET_CONSUMPTION")
COMMAND_GET_EVENTS = constant_id("COMMAND_GET_EVENTS")
COMMAND_GET_SENSOR_CONSUMPTION = constant_id("COMMAND_GET_SENSOR_CONSUMPTION")
COMMAND_GET_SERVICE_LOCATIONS = constant_id("COMMAND_GET_SERVICE_LOCATIONS")
COMMAND_GET_SERVICE_LOCATION_INFO = constant_id("COMMAND_GET_SERVICE_LOCATION_INFO")
COMMAND_INITIALISE = constant_id("COMMAND_INITIALISE")
COMMAND_NEW_ACTUATOR = constant_id("COMMAND_NEW_ACTUATOR")
COMMAND_NEW_APPLIANCE = constant_id("COMMAND_NEW_APPLIANCE")
COMMAND_NEW_SENSOR = constant_id("COMMAND_NEW_SENSOR")
COMMAND_OFF = constant_id("COMMAND_OFF")
COMMAND_ON = constant_id("COMMAND_ON")
COMMAND_REFRESH_TOKEN = constant_id("COMMAND_REFRESH_TOKEN")
COMMAND_RESET_CONSUMPTION = constant_id("COMMAND_RESET_CONSUMPTION")
COMMAND_RESET_SENSOR_CONSUMPTION = constant_id("COMMAND_RESET_SENSOR_CONSUMPTION")
CONFIG = constant_id("CONFIG")
CONSUMPTION_DATA_RECEIVED = constant_id("CONSUMPTION_DATA_RECEIVED")
CURRENCY_CODE = constant_id("CURRENCY_CODE")
CURRENT_ENERGY_LEVEL = constant_id("CURRENT_ENERGY_LEVEL")
CURRENT_UNITS = constant_id("CURRENT_UNITS")
CURRENT_UNITS_RATE = constant_id("CURRENT_UNITS_RATE")
DAILY_NET_TOTAL_COST = constant_id("DAILY_NET_TOTAL_COST")
DAILY_STANDING_CHARGE = constant_id("DAILY_STANDING_CHARGE")
DAILY_TOTAL_COST = constant_id("DAILY_TOTAL_COST")
DAILY_TOTAL_COST_SAVING = constant_id("DAILY_TOTAL_COST_SAVING")
DATETIME_STARTED = constant_id("DATETIME_STARTED")
DEFAULT = constant_id("DEFAULT")
DEVICES_FOLDER_ID = constant_id("DEVICES_FOLDER_ID")
DEVICE_TYPE = constant_id("DEVICE_TYPE")
DEV_ID = constant_id("DEV_ID")
ELECTRICITY_COST = constant_id("ELECTRICITY_COST")
ELECTRICITY_CURRENCY = constant_id("ELECTRICITY_CURRENCY")
ELECTRICITY_ID = constant_id("NAME")
ELECTRICITY_NET_ID = constant_id("ELECTRICITY_NET_ID")
ELECTRICITY_SAVED_ID = constant_id("ELECTRICITY_SAVED_ID")
ENABLED = constant_id("ENABLED")
END_THREAD = constant_id("SEND_THREAD")
EVENT = constant_id("EVENT")
EXPORT_PERCENTAGE = constant_id("EXPORT_PERCENTAGE")
EXPORT_RATE = constant_id("EXPORT_RATE")
EXPORT_TYPE = constant_id("EXPORT_TYPE")
FORCE_THREAD_END = constant_id("FORCE_THREAD_END")
FORMAT_CURRENT = constant_id("FORMAT_CURRENT")
FORMAT_CURRENT_DIVISOR = constant_id("FORMAT_CURRENT_DIVISOR")
FORMAT_TOTAL = constant_id("FORMAT_TOTAL")
FORMAT_TOTAL_DIVISOR = constant_id("FORMAT_TOTAL_DIVISOR")
FT_3 = constant_id("FT_3")
FUNCTION_ADD_UPDATE = constant_id("FUNCTION_ADD_UPDATE")
FUNCTION_DEQUEUE = constant_id("FUNCTION_DEQUEUE")
FUNCTION_QUEUE_ADD = constant_id("FUNCTION_QUEUE_ADD")
FUNCTION_QUEUE_REMOVE = constant_id("FUNCTION_QUEUE_REMOVE")
FUNCTION_STOP = constant_id("FUNCTION_STOP")
GALLONS = constant_id("GALLONS")
GENERATION_RATE = constant_id("GENERATION_RATE")
HIDE_ALWAYS_ON_POWER = constant_id("HIDE_ALWAYS_ON_POWER")
HIDE_ENERGY_METER_ACCUMULATED_NET_POWER = constant_id("HIDE_ENERGY_METER_ACCUMULATED_NET_POWER")
HIDE_ENERGY_METER_ACCUMULATED_NET_POWER_COST = constant_id("HIDE_ENERGY_METER_ACCUMULATED_NET_POWER_COST")
HIDE_ENERGY_METER_ACCUMULATED_POWER = constant_id("HIDE_ENERGY_METER_ACCUMULATED_POWER")
HIDE_ENERGY_METER_ACCUMULATED_POWER_COST = constant_id("HIDE_ENERGY_METER_ACCUMULATED_POWER_COST")
HIDE_ENERGY_METER_ACCUMULATED_SAVED_POWER = constant_id("HIDE_ENERGY_METER_ACCUMULATED_SAVED_POWER")
HIDE_ENERGY_METER_ACCUMULATED_SAVED_POWER_COST = constant_id("HIDE_ENERGY_METER_ACCUMULATED_SAVED_POWER_COST")
HIDE_ENERGY_METER_CURRENT_NET_POWER = constant_id("HIDE_ENERGY_METER_CURRENT_NET_POWER")
HIDE_ENERGY_METER_CURRENT_POWER = constant_id("HIDE_ENERGY_METER_CURRENT_POWER")
HIDE_ENERGY_METER_CURRENT_SAVED_POWER = constant_id("HIDE_ENERGY_METER_CURRENT_SAVED_POWER")
HIDE_ENERGY_METER_CURRENT_ZERO_NET_POWER = constant_id("HIDE_ENERGY_METER_CURRENT_ZERO_NET_POWER")
HIDE_NO_CHANGE_ENERGY_METER_ACCUMULATED_NET_POWER = constant_id("HIDE_NO_CHANGE_ENERGY_METER_ACCUMULATED_NET_POWER")
HIDE_NO_CHANGE_ENERGY_METER_ACCUMULATED_SAVED_POWER = constant_id("HIDE_NO_CHANGE_ENERGY_METER_ACCUMULATED_SAVED_POWER")
HIDE_NO_CHANGE_IN_SOLAR_EXPORTED_METER_ACCUMULATED_GENERATION = constant_id("HIDE_NO_CHANGE_IN_SOLAR_EXPORTED_METER_ACCUMULATED_GENERATION")
HIDE_NO_CHANGE_IN_SOLAR_METER_ACCUMULATED_GENERATION = constant_id("HIDE_NO_CHANGE_IN_SOLAR_METER_ACCUMULATED_GENERATION")
HIDE_NO_CHANGE_IN_SOLAR_USED_METER_ACCUMULATED_GENERATION = constant_id("HIDE_NO_CHANGE_IN_SOLAR_USED_METER_ACCUMULATED_GENERATION")
HIDE_SOLAR_EXPORTED_METER_ACCUMULATED_GENERATION = constant_id("HIDE_SOLAR_METER_CURRENT_GENERATION")
HIDE_SOLAR_EXPORTED_METER_CURRENT_GENERATION = constant_id("HIDE_SOLAR_METER_CURRENT_GENERATION")
HIDE_SOLAR_METER_ACCUMULATED_GENERATION = constant_id("HIDE_SOLAR_METER_ACCUMULATED_GENERATION")
HIDE_SOLAR_METER_ACCUMULATED_GENERATION_COST = constant_id("HIDE_SOLAR_METER_ACCUMULATED_GENERATION_COST")
HIDE_SOLAR_METER_CURRENT_GENERATION = constant_id("HIDE_SOLAR_METER_CURRENT_GENERATION")
HIDE_SOLAR_USED_METER_ACCUMULATED_GENERATION = constant_id("HIDE_SOLAR_USED_METER_ACCUMULATED_GENERATION")
HIDE_SOLAR_USED_METER_CURRENT_GENERATION = constant_id("HIDE_SOLAR_USED_METER_CURRENT_GENERATION")
HIDE_ZERO_SOLAR_METER_CURRENT_GENERATION = constant_id("HIDE_ZERO_SOLAR_METER_CURRENT_GENERATION")
HUMIDITY_LAST_UPDATED = constant_id("HUMIDITY_LAST_UPDATED")
INDIGO_SERVER_ADDRESS = constant_id("INDIGO_SERVER_ADDRESS")
INITIALISED = constant_id("INITIALISED")
KWH = constant_id("KWH")
KWH_UNIT_COST = constant_id("KWH_UNIT_COST")
LAST_READING_APPLIANCE = constant_id("LAST_READING_APPLIANCE")
LAST_READING_APPLIANCE_UTC = constant_id("LAST_READING_APPLIANCE_UTC")
LAST_READING_ELECTRICITY = constant_id("LAST_READING_ELECTRICITY")
LAST_READING_ELECTRICITY_NET = constant_id("LAST_READING_ELECTRICITY_NET")
LAST_READING_ELECTRICITY_NET_UTC = constant_id("LAST_READING_ELECTRICITY_NET_UTC")
LAST_READING_ELECTRICITY_SAVED = constant_id("LAST_READING_ELECTRICITY_SAVED")
LAST_READING_ELECTRICITY_SAVED_UTC = constant_id("LAST_READING_ELECTRICITY_SAVED_UTC")
LAST_READING_ELECTRICITY_UTC = constant_id("LAST_READING_ELECTRICITY_UTC")
LAST_READING_SENSOR = constant_id("LAST_READING_SENSOR")
LAST_READING_SENSOR_UTC = constant_id("LAST_READING_SENSOR_UTC")
LAST_READING_SOLAR = constant_id("LAST_READING_SOLAR")
LAST_READING_SOLAR_EXPORTED = constant_id("LAST_READING_SOLAR_EXPORTED")
LAST_READING_SOLAR_EXPORTED_UTC = constant_id("LAST_READING_SOLAR_EXPORTED_UTC")
LAST_READING_SOLAR_USED = constant_id("LAST_READING_SOLAR_USED")
LAST_READING_SOLAR_USED_UTC = constant_id("LAST_READING_SOLAR_USED_UTC")
LAST_READING_SOLAR_UTC = constant_id("LAST_READING_SOLAR_UTC")
LAST_RESET_APPLIANCE_UTC = constant_id("LAST_RESET_APPLIANCE_UTC")
LAST_RESET_ELECTRICITY_SAVED_UTC = constant_id("LAST_RESET_ELECTRICITY_SAVED_UTC")
LAST_RESET_ELECTRICITY_UTC= constant_id("LAST_RESET_ELECTRICITY_UTC")
LAST_RESET_ELECTRICITY_NET_UTC = constant_id("LAST_RESET_ELECTRICITY_NET_UTC")
LAST_RESET_SENSOR_UTC = constant_id("LAST_RESET_SENSOR_UTC")
LAST_RESET_SOLAR_EXPORTED_UTC = constant_id("LAST_RESET_SOLAR_EXPORTED_UTC")
LAST_RESET_SOLAR_USED_UTC = constant_id("LAST_RESET_SOLAR_USED_UTC")
LAST_RESET_SOLAR_UTC = constant_id("LAST_RESET_SOLAR_UTC")
LATITUDE = constant_id("LATITUDE")
LITRES = constant_id("LITRES")
LONGDITUDE = constant_id("LONGDITUDE")
MEASUREMENT_TIME_MULTIPLIER = constant_id("MEASUREMENT_TIME_MULTIPLIER")
M_3 = constant_id("M_3")
NAME = constant_id("NAME")
NEW_ACTUATOR = constant_id("NEW_ACTUATOR")
NEW_APPLIANCE = constant_id("NEW_APPLIANCE")
NEW_SENSOR = constant_id("NEW_SENSOR")
ON_OFF_STATE = constant_id("ON_OFF_STATE")
ON_OFF_STATE_BOOL = constant_id("ON_OFF_STATE_BOOL")
PASSWORD = constant_id("PASSWORD")
PATH = constant_id("PATH")
PLUGIN_DISPLAY_NAME = constant_id("PLUGIN_DISPLAY_NAME")
PLUGIN_ID = constant_id("PLUGIN_ID")
PLUGIN_INFO = constant_id("PLUGIN_INFO")
PLUGIN_INITIALIZED = constant_id("PLUGIN_INITIALIZED")
PLUGIN_PREFS_FOLDER = constant_id("PLUGIN_PREFS_FOLDER")
PLUGIN_VERSION = constant_id("PLUGIN_VERSION")
POLLING = constant_id("POLLING")
PROCESS = constant_id("PROCESS")
PULSES_PER_UNIT = constant_id("PULSES_PER_UNIT")
QUEUED_ADD = constant_id("QUEUED_ADD")
QUEUED_REMOVE = constant_id("QUEUED_REMOVE")
QUEUES = constant_id("QUEUES")
READINGS_LAST_UPDATED = constant_id("READINGS_LAST_UPDATED")
REFRESH_TOKEN = constant_id("REFRESH_TOKEN")
SECONDS = constant_id("SECONDS")
SECRET = constant_id("SECRET")
SEND_TO_SMAPPEE = constant_id("SEND_TO_SMAPPEE")
SENSOR_IDS = constant_id("SENSOR_IDS")
SERVICE_LOCATION_ID = constant_id("SERVICE_LOCATION_ID")
SERVICE_LOCATION_NAME = constant_id("SERVICE_LOCATION_NAME")
SMAPPEES = constant_id("SMAPPEES")
SMAPPEE_APPLIANCES = constant_id("SMAPPEE_APPLIANCES")
SMAPPEE_DEVICE_FOLDER = constant_id("SMAPPEE_DEVICE_FOLDER")
SMAPPEE_INTERFACE = constant_id("SMAPPEE_INTERFACE")
SMAPPEE_PLUGS = constant_id("SMAPPEE_PLUGS")
SMAPPEE_SERVICE_LOCATION_ID_TO_DEV_ID = constant_id("SMAPPEE_SERVICE_LOCATION_ID_TO_DEV_ID")
SMAPPEE_UNIT_COST = constant_id("SMAPPEE_UNIT_COST")
SMAPPEE_UNIT_CURRENCY = constant_id("SMAPPEE_UNIT_CURRENCY")
SOLAR_EXPORTED_ID = constant_id("SOLAR_EXPORTED_ID")
SOLAR_ID = constant_id("SOLAR_ID")
SOLAR_USED_ID = constant_id("SOLAR_USED_ID")
SQL = constant_id("SQL")
SQL_CONNECTION = constant_id("SQL_CONNECTION")
SQL_CURSOR = constant_id("SQL_CURSOR")
STATUS = constant_id("STATUS")
SUPPORTS_ELECTRICITY = constant_id("SUPPORTS_ELECTRICITY")
SUPPORTS_ELECTRICITY_NET = constant_id("SUPPORTS_ELECTRICITY_NET")
SUPPORTS_ELECTRICITY_SAVED = constant_id("SUPPORTS_ELECTRICITY_SAVED")
SUPPORTS_SENSOR = constant_id("SUPPORTS_SENSOR")
SUPPORTS_SOLAR = constant_id("SUPPORTS_SOLAR")
SUPPORTS_SOLAR_EXPORTED = constant_id("SUPPORTS_SOLAR_EXPORTED")
SUPPORTS_SOLAR_USED = constant_id("SUPPORTS_SOLAR_USED")
TEMPERATURE_LAST_UPDATED = constant_id("TEMPERATURE_LAST_UPDATED")
TESTING = constant_id("TESTING")
TEST_BATTERY_LEVEL = constant_id("TEST_BATTERY_LEVEL")
TEST_DATA = constant_id("TEST_DATA")
TEST_HUMIDITY = constant_id("TEST_HUMIDITY")
TEST_TEMPERATURE = constant_id("TEST_TEMPERATURE")
TEST_VALUE_1 = constant_id("TEST_VALUE_1")
TEST_VALUE_2 = constant_id("TEST_VALUE_2")
THREAD = constant_id("THREAD")
THREADS = constant_id("THREADS")
THREAD_ACTIVE = constant_id("THREAD_ACTIVE")
THREAD_END = constant_id("THREAD_END")
TOKEN_EXPIRES_DATETIME_UTC = constant_id("TOKEN_EXPIRES_DATETIME_UTC")
TOKEN_EXPIRES_IN = constant_id("TOKEN_EXPIRES_IN")
UNITS = constant_id("UNITS")
UNIT_COST = constant_id("UNIT_COST")
UNIT_TABLE = constant_id("UNIT_TABLE")
USER_NAME = constant_id("USER_NAME")

# OPTIONS_ENERGY_METER_CURRENT_POWER = constant_id("OPTIONS_ENERGY_METER_CURRENT_POWER")

LOG_LEVEL_NOT_SET = 0
LOG_LEVEL_DEBUGGING = 10
LOG_LEVEL_STARLING_API = 15
LOG_LEVEL_INFO = 20
LOG_LEVEL_WARNING = 30
LOG_LEVEL_ERROR = 40
LOG_LEVEL_CRITICAL = 50

LOG_LEVEL_TRANSLATION = dict()
LOG_LEVEL_TRANSLATION[LOG_LEVEL_NOT_SET] = "Not Set"
LOG_LEVEL_TRANSLATION[LOG_LEVEL_DEBUGGING] = "Debugging"
LOG_LEVEL_TRANSLATION[LOG_LEVEL_STARLING_API] = "Starling API Logging"
LOG_LEVEL_TRANSLATION[LOG_LEVEL_INFO] = "Info"
LOG_LEVEL_TRANSLATION[LOG_LEVEL_WARNING] = "Warning"
LOG_LEVEL_TRANSLATION[LOG_LEVEL_ERROR] = "Error"
LOG_LEVEL_TRANSLATION[LOG_LEVEL_CRITICAL] = "Critical"

SMAPPEE_POST_API_CALL = True
SMAPPEE_GET_API_CALL = False
